server.modules += (
    "mod_proxy",
    "mod_accesslog",
    "mod_setenv"
)

server.document-root = "/var/www/html"
server.port = 8080
server.bind = "0.0.0.0"

index-file.names = ( "index.html" )

# Allow React Router to handle HTML5 routing paths
server.error-handler-404 = "/index.html"

# Access log
accesslog.filename = "/dev/stderr"
setenv.set-request-header = (
    "X-Local-Job" => ""
)

# Proxy all requests to the Spring Boot API
proxy.server = (
    "/api" => (
        (
            "host" => "zbank-api",
            "port" => 8888
        )
    )
)
