---

- name: Get jury public key
  hosts: jury
  become: true
  tasks:
    - name: Slurp jury public key
      ansible.builtin.slurp:
        src: /etc/wireguard/public.key
      register: jury_pub_slurp
    - name: Expose jury_pubkey to all hosts (via hostvars)
      ansible.builtin.set_fact:
        jury_pubkey: "{{ jury_pub_slurp.content | b64decode | trim }}"

- name: restrict players to own vulnbox only
  hosts: player_core_*
  gather_facts: false
  become: true
  vars:
    team_id: "{{ (inventory_hostname | regex_search('\\d+$')) | int }}"
    allowed_ips_closed: "{{ lan_subnet }},10.80.{{ team_id }}.{{ vuln_host_suffix }}/32"
  tasks:
    - name: Assert jury_pubkey present
      ansible.builtin.assert:
        that:
          - hostvars['jury'].jury_pubkey is defined
        fail_msg: "jury_pubkey не найден: сперва отработай play 'Get jury public key'."

    - name: player_core -> jury AllowedIPs
      ansible.builtin.command:
        cmd: >
          wg set {{ lan }}
          peer {{ hostvars['jury'].jury_pubkey }}
          allowed-ips {{ allowed_ips_closed }}


- name: cut vulnbox cross-team on cores
  hosts: vulnbox_core_*
  gather_facts: false
  become: true
  vars:
    allowed_ips_closed: "{{ lan_subnet }}"
  tasks:
    - name: Assert jury_pubkey present
      ansible.builtin.assert:
        that:
          - hostvars['jury'].jury_pubkey is defined
    - name: vulnbox_core -> jury AllowedIPs
      ansible.builtin.command:
        cmd: >
          wg set {{ lan }}
          peer {{ hostvars['jury'].jury_pubkey }}
          allowed-ips {{ allowed_ips_closed }}
