teams:
  - name: "cR4.sh"
    id: 1
  - name: "0xb00b5"
    id: 2
  - name: "per aspera ad astra★"
    id: 3
  - name: "The power of Elijah"
    id: 4
  - name: "DUCKERZ"
    id: 5
  - name: "amigus"
    id: 6
  - name: "Drovosec"
    id: 7
  - name: "fTerryDavis"
    id: 8
  - name: "Chelobit'evo"
    id: 9
  - name: "Hack-trickers"
    id: 10
